# /etc/systemd/system/getty@tty1.service.d/override.conf
# Autologin na tty1 dla użytkownika "piotr" - podmień na swoją nazwę usera
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin piotr --noclear %I $TERM
